#!/bin/bash
# OpenFOAM passive-tracer reference for the finite-width 3D backward-facing step.
#
# Transports a passive scalar on the FROZEN converged flow of ../../bfs3d_openfoam, and writes the
# converged tracer field to ../runs/species/:
#   docker run --rm -v <repo root>:/work -w /work/validation/bfs3d_species/of_case \
#       openfoam13:latest bash run_of.sh
#
# This case deliberately carries NO mesh and NO flow of its own. It assembles a scratch case from
# the flow case's polyMesh and its converged time directory, so the tracer rides the same cells and
# the same face flux `phi` that the flow solved -- which is also the flux aquaflux is handed for the
# same-flux arm of the comparison. Splitting the inlet patch to make an injector was deliberately
# NOT done: the injection is a spatially varying boundary VALUE on the existing inlet (generated by
# write_inlet_field.py), so the polyMesh is untouched and every measurement taken on it stays valid.
set -e
cd "$(dirname "$0")"

FLOW=../../bfs3d_openfoam/of_case
START=2000
RUNS=../runs
DST="$RUNS/species"

if [ ! -f "$FLOW/$START/phi" ]; then
    echo "run_of: $FLOW/$START/phi is missing -- run the flow case first" >&2
    exit 1
fi
if [ ! -f 0.orig/s ]; then
    echo "run_of: 0.orig/s is missing -- run write_inlet_field.py first" >&2
    exit 1
fi

# Assemble the scratch case: the flow's mesh and physical properties, its converged fields, and the
# tracer's initial/boundary field. Everything here is regenerated on each run and is gitignored.
rm -rf constant "$START" [0-9]*.[0-9]* postProcessing log.* 2>/dev/null || true
mkdir -p constant
cp -r "$FLOW/constant/polyMesh" constant/polyMesh
cp "$FLOW/constant/momentumTransport" "$FLOW/constant/physicalProperties" constant/

mkdir -p "$START"
# The frozen flow: velocity, pressure, turbulence and -- the one that matters -- the face flux.
cp "$FLOW/$START"/{U,p,k,omega,nut,phi} "$START"/
cp 0.orig/s "$START"/s

foamRun > log.foamRun 2>&1 || true

T=$(foamListTimes -latestTime)
rm -rf "$DST"; mkdir -p "$DST"
cp "$T"/s "$DST"/
# The flux the tracer actually rode, copied beside it so the comparison can assert it is the same
# field aquaflux was handed rather than assuming it.
cp "$START"/phi "$DST"/
cp -r constant/polyMesh "$DST"/polyMesh 2>/dev/null || true

echo "bfs3d species: latestTime=$T  $(grep -c 'Solving for s' log.foamRun || echo 0) tracer solves" \
    | tee "$RUNS/summary.txt"
